version: "3"
services:
  app:
    build: .
    ports:
      - "5010:8080"
    links:
      - "db:redis"

  db:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - "6379:6370"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
networks:
  default:
    external:
      name: bithumb-backend-net