spring:
#  redis:
#    host: "host.docker.internal"
#    port: 6379
  application:
    name: kafka-producer

server:
  port: 5010
cloud:
  aws:
    credentials:
      accessKey: AKIA2SJCWGIOHZXVYN5I
      secretKey: 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
    s3:
      bucket: youngcha-coin-service
      key: coinlist/coin-list.json
    region:
      static: ap-northeast-2
    stack:
      auto: false

property:
  desturi: wss://pubwss.bithumb.com/pub/ws
  kafka:
    server: 3.36.162.130:9092
    topic: kafka-spring-producer-coin-test5
