spring:
  redis:
    host: "127.0.0.1"
    port: 6379
  application:
    name: kafka-producer

server:
  port: 8080

cloud:
  aws:
    credentials:
      accessKey: AKIA2SJCWGIOHZXVYN5I  // 암호키(1)
      secretKey: KFpI6M/M6TSYVTQt13MFnv9LrdU9QDzR3Kzm2Oc2 // 암호키(2)
    s3:
      bucket: youngcha-coin-service  // 버킷이름
    region:
      static: ap-northeast-2
    stack:
      auto: false